replicaCount: 1

image:
  repository: postgres
  tag: 16

postgres:
  user: admin
  password: mysecretpassword
  database: mydb

service:
  port: 5432
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi