replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: latest

echoText: "Hello from Helm-managed frontend"

service:
  type: NodePort
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi
