apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
  type: {{ .Values.service.type }}
